"""V2 repo manifest generated from .superpowers/sdd/repo_manifest_v2_source.md"""

# Category groups (preserves source ordering and duplicate category appearances).
REPOS_V2 = [
    {
        "category": "highest_priority",
        "display_name": "Highest-priority additions",
        "repos": [
            ("pmxt-dev", "pmxt"),
            ("pmxt-dev", "pmxt-mcp"),
            ("Polymarket", "py-clob-client"),
            ("Polymarket", "agents"),
            ("gnosis", "prediction-market-agent-tooling"),
            ("microprediction", "manifoldbot"),
            ("GodlyPeeta", "prediction-markets.py"),
            ("gtg7784", "dr-manhattan-ts"),
            ("gtg7784", "dr-manhattan-rust"),
            ("erickdronski", "kalshi-polymarket-trader"),
            ("suislanchez", "polymarket-kalshi-weather-bot"),
            ("ryanfrigo", "kalshi-ai-trading-bot"),
            ("OctagonAI", "kalshi-trading-bot-cli"),
            ("ImMike", "polymarket-arbitrage"),
            ("CarlosIbCu", "polymarket-kalshi-btc-arbitrage-bot"),
            ("braedonsaunders", "homerun"),
            ("PredictionXBT", "PredictOS"),
            ("realfishsam", "prediction-market-arbitrage-bot"),
            ("kmizzi", "karb"),
            ("Drakkar-Software", "OctoBot-Prediction-Market"),
            ("mihai-stancescu", "polymarket-ai-trade-bot"),
        ],
    },
    {
        "category": "prediction_market_native",
        "display_name": "1. Prediction-market native repos",
        "repos": [
            ("Kalshi", "kalshi-starter-code-python"),
            ("Kalshi", "tools-and-analysis"),
            ("TexasCoding", "kalshi-python-sdk"),
            ("arshka", "pykalshi"),
            ("humz2k", "kalshi-python-unofficial"),
            ("vaguenebula", "kalshi-client"),
            ("AndrewNolte", "KalshiPythonClient"),
            ("EllAchE", "kalshi_cli"),
            ("Polymarket", "py-clob-client"),
            ("Polymarket", "clob-client-v2"),
            ("Polymarket", "agents"),
            ("pmxt-dev", "pmxt"),
            ("pmxt-dev", "pmxt-mcp"),
            ("GodlyPeeta", "prediction-markets.py"),
            ("gtg7784", "dr-manhattan-ts"),
            ("gtg7784", "dr-manhattan-rust"),
            ("microprediction", "manifoldbot"),
            ("gnosis", "prediction-market-agent-tooling"),
            ("quantified-uncertainty", "metaforecast"),
            ("vigji", "mootlib"),
        ],
    },
    {
        "category": "kalshi_polymarket_arbitrage",
        "display_name": "2. Kalshi / Polymarket arbitrage and execution bots",
        "repos": [
            ("ryanfrigo", "kalshi-ai-trading-bot"),
            ("OctagonAI", "kalshi-trading-bot-cli"),
            ("ImMike", "polymarket-arbitrage"),
            ("CarlosIbCu", "polymarket-kalshi-btc-arbitrage-bot"),
            ("realfishsam", "prediction-market-arbitrage-bot"),
            ("kmizzi", "karb"),
            ("tswaim", "polymarket-kalshi-arbitrage-bot"),
            ("Longbridges", "polymarket-kalshi-arbitrage-bot"),
            ("defi-ape", "polymarket-kalshi-arbitrage-bot"),
            ("TopTrenDev", "polymarket-kalshi-arbitrage-bot"),
            ("erickdronski", "kalshi-polymarket-trader"),
            ("braedonsaunders", "homerun"),
            ("PredictionXBT", "PredictOS"),
            ("ashercn97", "predmarket"),
            ("suislanchez", "polymarket-kalshi-weather-bot"),
            ("Drakkar-Software", "OctoBot-Prediction-Market"),
            ("mihai-stancescu", "polymarket-ai-trade-bot"),
            ("aulekator", "Polymarket-BTC-15-Minute-Trading-Bot"),
            ("discountifu", "polymarket-trading-bot"),
            ("Ronesfe", "Polymarket-Automated-Trading-Bot"),
            ("Anmoldureha", "polymarket-trading-bot-strategies"),
        ],
    },
    {
        "category": "sports_prediction_odds",
        "display_name": "3. Sports prediction / odds repos",
        "repos": [
            ("the-odds-api", "samples-python"),
            ("odds-api", "odds-api"),
            ("Sharp-API", "SharpAPI-TS"),
            ("carterlasalle", "SportsArbFinder"),
            ("daankoning", "ArbitrageFinder"),
            ("robbiehaynes", "arbitrage-finder"),
            ("ratsam3474", "autoarbitrage"),
            ("personal-coding", "Live-Sports-Arbitrage-Bet-Finder"),
            ("jhonatan-dev", "Betting-Arbitrage"),
            ("lumunge", "Arb"),
            ("odds-api", "arbitrage-betting-scanner-bot"),
            ("jordantete", "OddsHarvester"),
            ("pierridotite", "ArbitrageOdds"),
            ("lines64", "True-Odds-Calculator"),
            ("WFord26", "BetTrack"),
            ("coryypeters", "nrl-odds-intelligence-pipeline"),
            ("georgedouzas", "sports-betting"),
            ("NBA-Betting", "NBA_Betting"),
            ("IanDublew", "Machine-Learning-Football-Soccer-Prediction-Model-"),
            ("ronyka77", "SoccerPredictor_byRichardSzita"),
            ("manuelpeba", "world-cup-2026-forecast"),
            ("nickpadd", "EuropeanFootballLeaguePredictor"),
            ("msoczi", "football_predictions"),
            ("ratloop", "MatchOutcomeAI"),
            ("siddhu21", "Powerplay-Based-IPL-Match-Prediction"),
        ],
    },
    {
        "category": "weather_prediction_market",
        "display_name": "4. Weather prediction-market repos",
        "repos": [
            ("suislanchez", "polymarket-kalshi-weather-bot"),
            ("erickdronski", "kalshi-polymarket-trader"),
            ("open-meteo", "open-meteo"),
            ("paulokuong", "noaa"),
            ("weather-mcp", "weather-mcp"),
            ("GClunies", "noaa_coops"),
            ("tlaceby", "weather"),
            ("nst-guide", "ndfd_current"),
            ("jessehamner", "WeatherWidget"),
            ("Hrishikesh332", "Weather-Forecasting-Using-Ml"),
            ("Adhokshaj04", "weather_predict"),
            ("abz-mhd", "ai-weather-forecasting"),
            ("miketobz", "ML-Rainfall-Prediction"),
            ("mohsin-riad", "future-weather-forecasting"),
            ("kshitizrohilla", "weather-app-using-openweathermap-api"),
        ],
    },
    {
        "category": "stocks_equities_options_macro",
        "display_name": "5. Stocks / equities / options / macro repos",
        "repos": [
            ("microsoft", "qlib"),
            ("microsoft", "RD-Agent"),
            ("QuantConnect", "Lean"),
            ("QuantConnect", "Lean.Brokerages.InteractiveBrokers"),
            ("nautechsystems", "nautilus_trader"),
            ("polakowo", "vectorbt"),
            ("backtrader", "backtrader"),
            ("mementum", "backtrader"),
            ("kernc", "backtesting.py"),
            ("zipline-reloaded", "zipline-reloaded"),
            ("quantrocket-llc", "zipline"),
            ("StockSharp", "StockSharp"),
            ("coding-kitties", "investing-algorithm-framework"),
            ("kieran-mackle", "AutoTrader"),
            ("Lumiwealth", "lumibot"),
            ("marketcalls", "openalgo"),
            ("Doggie52", "Lean-Batch-Launcher"),
            ("vrindger", "actually_open_lean"),
            ("aarjaneiro", "QtLean"),
            ("AI4Finance-Foundation", "Awesome_AI4Finance"),
            ("huseinzol05", "Stock-Prediction-Models"),
            ("shirosaidev", "stocksight"),
            ("stefan-jansen", "machine-learning-for-trading"),
            ("shashankvemuri", "Finance"),
            ("HusseinJammal", "Liquid-Neural-Networks-in-Stock-Market-Prediction"),
            ("louisowen6", "SENN"),
            ("0xpranjal", "Stock-Prediction-using-different-models"),
            ("PyFi-Training", "Stock-Price-Forecasting-with-Machine-Learning"),
            ("jinglescode", "time-series-forecasting-pytorch"),
            ("Vatshayan", "Final-Year-Machine-Learning-Stock-Price-Prediction-Project"),
            ("virajbhutada", "Google-Stock-Price-Forecasting-LSTM"),
            ("gsaini", "financial-research-analyst-agent"),
            ("devfinwiz", "Fin-Maestro-Web"),
            ("navam-io", "navam-invest"),
            ("s-kerin", "finance_calendars"),
            ("cfdude", "mcp-finnhub"),
        ],
    },
    {
        "category": "commodities_energy_agriculture",
        "display_name": "6. Commodities / energy / agriculture repos",
        "repos": [
            ("NDelventhal", "cot_reports"),
            ("philsv", "pycot"),
            ("Mcamin", "cftc-cot"),
            ("Mcamin", "cot-analysis"),
            ("jensolson", "CFTC-COT"),
            ("MarcinLinkl", "Positions-CoT-Explorer"),
            ("philsv", "myeia"),
            ("EIAgov", "dash-benchmark"),
            ("OilpriceAPI", "python-sdk"),
            ("OilpriceAPI", "oilpriceapi-node"),
            ("datasets", "oil-prices"),
            ("omkarcloud", "commodity-price-api"),
            ("aedessler", "EIA-predictions"),
            ("gabsbruh", "price-forecasting"),
            ("robindevelops", "btc-forex-gold-silver-price-predictor"),
            ("BaseMax", "XAUUSD-LSTM"),
            ("je-suis-tm", "quant-trading"),
        ],
    },
    {
        "category": "crypto_btc_event_market",
        "display_name": "7. Crypto / BTC event-market repos",
        "repos": [
            ("ccxt", "ccxt"),
            ("freqtrade", "freqtrade"),
            ("hummingbot", "hummingbot"),
            ("Drakkar-Software", "OctoBot"),
            ("Drakkar-Software", "OctoBot-Market-Making"),
            ("nelso0", "barbotine-arbitrage-bot"),
            ("nkaz001", "hftbacktest"),
            ("ccxt", "binance-trade-bot"),
            ("Laser420", "fund_arb_bot"),
            ("nexwave-so", "energy-operator"),
            ("second-state", "fintool"),
            ("moss-site", "moss-trade-bot-skills"),
            ("Mattbusel", "FinRL_DeepSeek_Crypto_Trading"),
            ("botcrypto-io", "awesome-crypto-trading-bots"),
            ("suenot", "awesome-ccxt"),
        ],
    },
    {
        "category": "universal_ml_forecasting_optimization",
        "display_name": "8. Universal ML / forecasting / optimization stack",
        "repos": [
            ("unit8co", "darts"),
            ("autogluon", "autogluon"),
            ("optuna", "optuna"),
            ("optuna", "optuna-dashboard"),
            ("optuna", "optunahub"),
            ("statsmodels", "statsmodels"),
            ("scikit-learn", "scikit-learn"),
            ("scipy", "scipy"),
            ("numpy", "numpy"),
            ("pandas-dev", "pandas"),
            ("dmlc", "xgboost"),
            ("microsoft", "LightGBM"),
            ("catboost", "catboost"),
            ("Nixtla", "statsforecast"),
            ("Nixtla", "mlforecast"),
            ("Nixtla", "neuralforecast"),
            ("Nixtla", "hierarchicalforecast"),
            ("Nixtla", "utilsforecast"),
            ("facebook", "prophet"),
            ("timeseriesAI", "tsai"),
            ("pytorch", "pytorch"),
            ("lightning-ai", "pytorch-lightning"),
            ("ray-project", "ray"),
            ("DEAP", "deap"),
            ("automl", "auto-sklearn"),
            ("EpistasisLab", "tpot"),
            ("mlflow", "mlflow"),
            ("wandb", "wandb"),
            ("great-expectations", "great_expectations"),
            ("evidentlyai", "evidently"),
            ("Arize-ai", "phoenix"),
        ],
    },
    {
        "category": "financial_data_market_data",
        "display_name": "9. Financial data / market data layer",
        "repos": [
            ("OpenBB-finance", "OpenBB"),
            ("yfinance", "yfinance"),
            ("ranaroussi", "yfinance"),
            ("ranaroussi", "quantstats"),
            ("quantopian", "pyfolio"),
            ("quantopian", "empyrical"),
            ("ranaroussi", "empyrical"),
            ("pmorissette", "bt"),
            ("twopirllc", "pandas-ta"),
            ("bukosabino", "ta"),
            ("duckdb", "duckdb"),
            ("polarsource", "polars"),
        ],
    },
    {
        "category": "dashboard_api_observability",
        "display_name": "10. Dashboard / API / observability repos",
        "repos": [
            ("fastapi", "fastapi"),
            ("encode", "starlette"),
            ("encode", "uvicorn"),
            ("tiangolo", "full-stack-fastapi-template"),
            ("vitejs", "vite"),
            ("vercel", "next.js"),
            ("tailwindlabs", "tailwindcss"),
            ("recharts", "recharts"),
            ("streamlit", "streamlit"),
            ("plotly", "dash"),
            ("grafana", "grafana"),
            ("getredash", "redash"),
            ("metabase", "metabase"),
            ("ClickHouse", "ClickHouse"),
            ("duckdb", "duckdb"),
            ("redis", "redis"),
            ("prometheus", "prometheus"),
            ("grafana", "loki"),
        ],
    },
    {
        "category": "agent_automation_evaluation",
        "display_name": "11. Agent / automation / evaluation repos",
        "repos": [
            ("openai", "openai-agents-python"),
            ("microsoft", "autogen"),
            ("crewAIInc", "crewAI"),
            ("langchain-ai", "langchain"),
            ("langchain-ai", "langgraph"),
            ("run-llama", "llama_index"),
            ("SWE-agent", "SWE-agent"),
            ("aider-AI", "aider"),
            ("All-Hands-AI", "OpenHands"),
            ("BerriAI", "litellm"),
            ("promptfoo", "promptfoo"),
            ("Br0ski777", "x402-agent-tools"),
            ("BlockRunAI", "awesome-blockrun"),
            ("BlockRunAI", "blockrun-llm"),
            ("punkpeye", "awesome-mcp-servers"),
            ("TensorBlock", "awesome-mcp-servers"),
        ],
    },
]

# Flat, de-duplicated list: one entry per unique repo mapped to its first category.
ALL_REPOS_V2 = [
    ("pmxt-dev", "pmxt", "highest_priority"),
    ("pmxt-dev", "pmxt-mcp", "highest_priority"),
    ("Polymarket", "py-clob-client", "highest_priority"),
    ("Polymarket", "agents", "highest_priority"),
    ("gnosis", "prediction-market-agent-tooling", "highest_priority"),
    ("microprediction", "manifoldbot", "highest_priority"),
    ("GodlyPeeta", "prediction-markets.py", "highest_priority"),
    ("gtg7784", "dr-manhattan-ts", "highest_priority"),
    ("gtg7784", "dr-manhattan-rust", "highest_priority"),
    ("erickdronski", "kalshi-polymarket-trader", "highest_priority"),
    ("suislanchez", "polymarket-kalshi-weather-bot", "highest_priority"),
    ("ryanfrigo", "kalshi-ai-trading-bot", "highest_priority"),
    ("OctagonAI", "kalshi-trading-bot-cli", "highest_priority"),
    ("ImMike", "polymarket-arbitrage", "highest_priority"),
    ("CarlosIbCu", "polymarket-kalshi-btc-arbitrage-bot", "highest_priority"),
    ("braedonsaunders", "homerun", "highest_priority"),
    ("PredictionXBT", "PredictOS", "highest_priority"),
    ("realfishsam", "prediction-market-arbitrage-bot", "highest_priority"),
    ("kmizzi", "karb", "highest_priority"),
    ("Drakkar-Software", "OctoBot-Prediction-Market", "highest_priority"),
    ("mihai-stancescu", "polymarket-ai-trade-bot", "highest_priority"),
    ("Kalshi", "kalshi-starter-code-python", "prediction_market_native"),
    ("Kalshi", "tools-and-analysis", "prediction_market_native"),
    ("TexasCoding", "kalshi-python-sdk", "prediction_market_native"),
    ("arshka", "pykalshi", "prediction_market_native"),
    ("humz2k", "kalshi-python-unofficial", "prediction_market_native"),
    ("vaguenebula", "kalshi-client", "prediction_market_native"),
    ("AndrewNolte", "KalshiPythonClient", "prediction_market_native"),
    ("EllAchE", "kalshi_cli", "prediction_market_native"),
    ("Polymarket", "clob-client-v2", "prediction_market_native"),
    ("quantified-uncertainty", "metaforecast", "prediction_market_native"),
    ("vigji", "mootlib", "prediction_market_native"),
    ("tswaim", "polymarket-kalshi-arbitrage-bot", "kalshi_polymarket_arbitrage"),
    ("Longbridges", "polymarket-kalshi-arbitrage-bot", "kalshi_polymarket_arbitrage"),
    ("defi-ape", "polymarket-kalshi-arbitrage-bot", "kalshi_polymarket_arbitrage"),
    ("TopTrenDev", "polymarket-kalshi-arbitrage-bot", "kalshi_polymarket_arbitrage"),
    ("ashercn97", "predmarket", "kalshi_polymarket_arbitrage"),
    ("aulekator", "Polymarket-BTC-15-Minute-Trading-Bot", "kalshi_polymarket_arbitrage"),
    ("discountifu", "polymarket-trading-bot", "kalshi_polymarket_arbitrage"),
    ("Ronesfe", "Polymarket-Automated-Trading-Bot", "kalshi_polymarket_arbitrage"),
    ("Anmoldureha", "polymarket-trading-bot-strategies", "kalshi_polymarket_arbitrage"),
    ("the-odds-api", "samples-python", "sports_prediction_odds"),
    ("odds-api", "odds-api", "sports_prediction_odds"),
    ("Sharp-API", "SharpAPI-TS", "sports_prediction_odds"),
    ("carterlasalle", "SportsArbFinder", "sports_prediction_odds"),
    ("daankoning", "ArbitrageFinder", "sports_prediction_odds"),
    ("robbiehaynes", "arbitrage-finder", "sports_prediction_odds"),
    ("ratsam3474", "autoarbitrage", "sports_prediction_odds"),
    ("personal-coding", "Live-Sports-Arbitrage-Bet-Finder", "sports_prediction_odds"),
    ("jhonatan-dev", "Betting-Arbitrage", "sports_prediction_odds"),
    ("lumunge", "Arb", "sports_prediction_odds"),
    ("odds-api", "arbitrage-betting-scanner-bot", "sports_prediction_odds"),
    ("jordantete", "OddsHarvester", "sports_prediction_odds"),
    ("pierridotite", "ArbitrageOdds", "sports_prediction_odds"),
    ("lines64", "True-Odds-Calculator", "sports_prediction_odds"),
    ("WFord26", "BetTrack", "sports_prediction_odds"),
    ("coryypeters", "nrl-odds-intelligence-pipeline", "sports_prediction_odds"),
    ("georgedouzas", "sports-betting", "sports_prediction_odds"),
    ("NBA-Betting", "NBA_Betting", "sports_prediction_odds"),
    ("IanDublew", "Machine-Learning-Football-Soccer-Prediction-Model-", "sports_prediction_odds"),
    ("ronyka77", "SoccerPredictor_byRichardSzita", "sports_prediction_odds"),
    ("manuelpeba", "world-cup-2026-forecast", "sports_prediction_odds"),
    ("nickpadd", "EuropeanFootballLeaguePredictor", "sports_prediction_odds"),
    ("msoczi", "football_predictions", "sports_prediction_odds"),
    ("ratloop", "MatchOutcomeAI", "sports_prediction_odds"),
    ("siddhu21", "Powerplay-Based-IPL-Match-Prediction", "sports_prediction_odds"),
    ("open-meteo", "open-meteo", "weather_prediction_market"),
    ("paulokuong", "noaa", "weather_prediction_market"),
    ("weather-mcp", "weather-mcp", "weather_prediction_market"),
    ("GClunies", "noaa_coops", "weather_prediction_market"),
    ("tlaceby", "weather", "weather_prediction_market"),
    ("nst-guide", "ndfd_current", "weather_prediction_market"),
    ("jessehamner", "WeatherWidget", "weather_prediction_market"),
    ("Hrishikesh332", "Weather-Forecasting-Using-Ml", "weather_prediction_market"),
    ("Adhokshaj04", "weather_predict", "weather_prediction_market"),
    ("abz-mhd", "ai-weather-forecasting", "weather_prediction_market"),
    ("miketobz", "ML-Rainfall-Prediction", "weather_prediction_market"),
    ("mohsin-riad", "future-weather-forecasting", "weather_prediction_market"),
    ("kshitizrohilla", "weather-app-using-openweathermap-api", "weather_prediction_market"),
    ("microsoft", "qlib", "stocks_equities_options_macro"),
    ("microsoft", "RD-Agent", "stocks_equities_options_macro"),
    ("QuantConnect", "Lean", "stocks_equities_options_macro"),
    ("QuantConnect", "Lean.Brokerages.InteractiveBrokers", "stocks_equities_options_macro"),
    ("nautechsystems", "nautilus_trader", "stocks_equities_options_macro"),
    ("polakowo", "vectorbt", "stocks_equities_options_macro"),
    ("backtrader", "backtrader", "stocks_equities_options_macro"),
    ("mementum", "backtrader", "stocks_equities_options_macro"),
    ("kernc", "backtesting.py", "stocks_equities_options_macro"),
    ("zipline-reloaded", "zipline-reloaded", "stocks_equities_options_macro"),
    ("quantrocket-llc", "zipline", "stocks_equities_options_macro"),
    ("StockSharp", "StockSharp", "stocks_equities_options_macro"),
    ("coding-kitties", "investing-algorithm-framework", "stocks_equities_options_macro"),
    ("kieran-mackle", "AutoTrader", "stocks_equities_options_macro"),
    ("Lumiwealth", "lumibot", "stocks_equities_options_macro"),
    ("marketcalls", "openalgo", "stocks_equities_options_macro"),
    ("Doggie52", "Lean-Batch-Launcher", "stocks_equities_options_macro"),
    ("vrindger", "actually_open_lean", "stocks_equities_options_macro"),
    ("aarjaneiro", "QtLean", "stocks_equities_options_macro"),
    ("AI4Finance-Foundation", "Awesome_AI4Finance", "stocks_equities_options_macro"),
    ("huseinzol05", "Stock-Prediction-Models", "stocks_equities_options_macro"),
    ("shirosaidev", "stocksight", "stocks_equities_options_macro"),
    ("stefan-jansen", "machine-learning-for-trading", "stocks_equities_options_macro"),
    ("shashankvemuri", "Finance", "stocks_equities_options_macro"),
    ("HusseinJammal", "Liquid-Neural-Networks-in-Stock-Market-Prediction", "stocks_equities_options_macro"),
    ("louisowen6", "SENN", "stocks_equities_options_macro"),
    ("0xpranjal", "Stock-Prediction-using-different-models", "stocks_equities_options_macro"),
    ("PyFi-Training", "Stock-Price-Forecasting-with-Machine-Learning", "stocks_equities_options_macro"),
    ("jinglescode", "time-series-forecasting-pytorch", "stocks_equities_options_macro"),
    ("Vatshayan", "Final-Year-Machine-Learning-Stock-Price-Prediction-Project", "stocks_equities_options_macro"),
    ("virajbhutada", "Google-Stock-Price-Forecasting-LSTM", "stocks_equities_options_macro"),
    ("gsaini", "financial-research-analyst-agent", "stocks_equities_options_macro"),
    ("devfinwiz", "Fin-Maestro-Web", "stocks_equities_options_macro"),
    ("navam-io", "navam-invest", "stocks_equities_options_macro"),
    ("s-kerin", "finance_calendars", "stocks_equities_options_macro"),
    ("cfdude", "mcp-finnhub", "stocks_equities_options_macro"),
    ("NDelventhal", "cot_reports", "commodities_energy_agriculture"),
    ("philsv", "pycot", "commodities_energy_agriculture"),
    ("Mcamin", "cftc-cot", "commodities_energy_agriculture"),
    ("Mcamin", "cot-analysis", "commodities_energy_agriculture"),
    ("jensolson", "CFTC-COT", "commodities_energy_agriculture"),
    ("MarcinLinkl", "Positions-CoT-Explorer", "commodities_energy_agriculture"),
    ("philsv", "myeia", "commodities_energy_agriculture"),
    ("EIAgov", "dash-benchmark", "commodities_energy_agriculture"),
    ("OilpriceAPI", "python-sdk", "commodities_energy_agriculture"),
    ("OilpriceAPI", "oilpriceapi-node", "commodities_energy_agriculture"),
    ("datasets", "oil-prices", "commodities_energy_agriculture"),
    ("omkarcloud", "commodity-price-api", "commodities_energy_agriculture"),
    ("aedessler", "EIA-predictions", "commodities_energy_agriculture"),
    ("gabsbruh", "price-forecasting", "commodities_energy_agriculture"),
    ("robindevelops", "btc-forex-gold-silver-price-predictor", "commodities_energy_agriculture"),
    ("BaseMax", "XAUUSD-LSTM", "commodities_energy_agriculture"),
    ("je-suis-tm", "quant-trading", "commodities_energy_agriculture"),
    ("ccxt", "ccxt", "crypto_btc_event_market"),
    ("freqtrade", "freqtrade", "crypto_btc_event_market"),
    ("hummingbot", "hummingbot", "crypto_btc_event_market"),
    ("Drakkar-Software", "OctoBot", "crypto_btc_event_market"),
    ("Drakkar-Software", "OctoBot-Market-Making", "crypto_btc_event_market"),
    ("nelso0", "barbotine-arbitrage-bot", "crypto_btc_event_market"),
    ("nkaz001", "hftbacktest", "crypto_btc_event_market"),
    ("ccxt", "binance-trade-bot", "crypto_btc_event_market"),
    ("Laser420", "fund_arb_bot", "crypto_btc_event_market"),
    ("nexwave-so", "energy-operator", "crypto_btc_event_market"),
    ("second-state", "fintool", "crypto_btc_event_market"),
    ("moss-site", "moss-trade-bot-skills", "crypto_btc_event_market"),
    ("Mattbusel", "FinRL_DeepSeek_Crypto_Trading", "crypto_btc_event_market"),
    ("botcrypto-io", "awesome-crypto-trading-bots", "crypto_btc_event_market"),
    ("suenot", "awesome-ccxt", "crypto_btc_event_market"),
    ("unit8co", "darts", "universal_ml_forecasting_optimization"),
    ("autogluon", "autogluon", "universal_ml_forecasting_optimization"),
    ("optuna", "optuna", "universal_ml_forecasting_optimization"),
    ("optuna", "optuna-dashboard", "universal_ml_forecasting_optimization"),
    ("optuna", "optunahub", "universal_ml_forecasting_optimization"),
    ("statsmodels", "statsmodels", "universal_ml_forecasting_optimization"),
    ("scikit-learn", "scikit-learn", "universal_ml_forecasting_optimization"),
    ("scipy", "scipy", "universal_ml_forecasting_optimization"),
    ("numpy", "numpy", "universal_ml_forecasting_optimization"),
    ("pandas-dev", "pandas", "universal_ml_forecasting_optimization"),
    ("dmlc", "xgboost", "universal_ml_forecasting_optimization"),
    ("microsoft", "LightGBM", "universal_ml_forecasting_optimization"),
    ("catboost", "catboost", "universal_ml_forecasting_optimization"),
    ("Nixtla", "statsforecast", "universal_ml_forecasting_optimization"),
    ("Nixtla", "mlforecast", "universal_ml_forecasting_optimization"),
    ("Nixtla", "neuralforecast", "universal_ml_forecasting_optimization"),
    ("Nixtla", "hierarchicalforecast", "universal_ml_forecasting_optimization"),
    ("Nixtla", "utilsforecast", "universal_ml_forecasting_optimization"),
    ("facebook", "prophet", "universal_ml_forecasting_optimization"),
    ("timeseriesAI", "tsai", "universal_ml_forecasting_optimization"),
    ("pytorch", "pytorch", "universal_ml_forecasting_optimization"),
    ("lightning-ai", "pytorch-lightning", "universal_ml_forecasting_optimization"),
    ("ray-project", "ray", "universal_ml_forecasting_optimization"),
    ("DEAP", "deap", "universal_ml_forecasting_optimization"),
    ("automl", "auto-sklearn", "universal_ml_forecasting_optimization"),
    ("EpistasisLab", "tpot", "universal_ml_forecasting_optimization"),
    ("mlflow", "mlflow", "universal_ml_forecasting_optimization"),
    ("wandb", "wandb", "universal_ml_forecasting_optimization"),
    ("great-expectations", "great_expectations", "universal_ml_forecasting_optimization"),
    ("evidentlyai", "evidently", "universal_ml_forecasting_optimization"),
    ("Arize-ai", "phoenix", "universal_ml_forecasting_optimization"),
    ("OpenBB-finance", "OpenBB", "financial_data_market_data"),
    ("yfinance", "yfinance", "financial_data_market_data"),
    ("ranaroussi", "yfinance", "financial_data_market_data"),
    ("ranaroussi", "quantstats", "financial_data_market_data"),
    ("quantopian", "pyfolio", "financial_data_market_data"),
    ("quantopian", "empyrical", "financial_data_market_data"),
    ("ranaroussi", "empyrical", "financial_data_market_data"),
    ("pmorissette", "bt", "financial_data_market_data"),
    ("twopirllc", "pandas-ta", "financial_data_market_data"),
    ("bukosabino", "ta", "financial_data_market_data"),
    ("duckdb", "duckdb", "financial_data_market_data"),
    ("polarsource", "polars", "financial_data_market_data"),
    ("fastapi", "fastapi", "dashboard_api_observability"),
    ("encode", "starlette", "dashboard_api_observability"),
    ("encode", "uvicorn", "dashboard_api_observability"),
    ("tiangolo", "full-stack-fastapi-template", "dashboard_api_observability"),
    ("vitejs", "vite", "dashboard_api_observability"),
    ("vercel", "next.js", "dashboard_api_observability"),
    ("tailwindlabs", "tailwindcss", "dashboard_api_observability"),
    ("recharts", "recharts", "dashboard_api_observability"),
    ("streamlit", "streamlit", "dashboard_api_observability"),
    ("plotly", "dash", "dashboard_api_observability"),
    ("grafana", "grafana", "dashboard_api_observability"),
    ("getredash", "redash", "dashboard_api_observability"),
    ("metabase", "metabase", "dashboard_api_observability"),
    ("ClickHouse", "ClickHouse", "dashboard_api_observability"),
    ("redis", "redis", "dashboard_api_observability"),
    ("prometheus", "prometheus", "dashboard_api_observability"),
    ("grafana", "loki", "dashboard_api_observability"),
    ("openai", "openai-agents-python", "agent_automation_evaluation"),
    ("microsoft", "autogen", "agent_automation_evaluation"),
    ("crewAIInc", "crewAI", "agent_automation_evaluation"),
    ("langchain-ai", "langchain", "agent_automation_evaluation"),
    ("langchain-ai", "langgraph", "agent_automation_evaluation"),
    ("run-llama", "llama_index", "agent_automation_evaluation"),
    ("SWE-agent", "SWE-agent", "agent_automation_evaluation"),
    ("aider-AI", "aider", "agent_automation_evaluation"),
    ("All-Hands-AI", "OpenHands", "agent_automation_evaluation"),
    ("BerriAI", "litellm", "agent_automation_evaluation"),
    ("promptfoo", "promptfoo", "agent_automation_evaluation"),
    ("Br0ski777", "x402-agent-tools", "agent_automation_evaluation"),
    ("BlockRunAI", "awesome-blockrun", "agent_automation_evaluation"),
    ("BlockRunAI", "blockrun-llm", "agent_automation_evaluation"),
    ("punkpeye", "awesome-mcp-servers", "agent_automation_evaluation"),
    ("TensorBlock", "awesome-mcp-servers", "agent_automation_evaluation"),
]

# Backward-compatible flat list used by legacy consumers (no category).
MANDATORY_REPOS = [(owner, name) for owner, name, _category in ALL_REPOS_V2]
