from __future__ import annotations

from tests.v35_test_helpers import assert_current_test_report, v35_reports


def test_v34_still_passes_or_partial_expected() -> None:
    report = assert_current_test_report(__file__)
    assert report["mission_state_verdict"] == "PARTIAL"
    assert report["v34_operator_enabled_probe_run_reconciliation_status"] == "PASS_PARTIAL_EXPECTED"
    assert report["v34_qc_confirmation_status"] == "PASS"
    assert report["live_submit_flag_status"] == "PASS_DISABLED"
    assert report["caps_config_status"] == "PASS_UNCHANGED"


def test_v34_baseline_reports_still_present() -> None:
    reports = v35_reports()
    # V34 final report must still exist as an artifact (generated by generate_v34_reports.py).
    from pathlib import Path

    root = Path(__file__).resolve().parents[1]
    v34_final = root / "artifacts" / "dummy" / "final_report_v34.json"
    assert v34_final.exists()
