from __future__ import annotations

PROMOTED_ADAPTER_NAMES: list[str] = [
    "SharpAPI_TS_adapter",
    "arbitrage_betting_scanner_bot_adapter",
    "NBA_Betting_adapter",
    "world_cup_2026_forecast_adapter",
    "EuropeanFootballLeaguePredictor_adapter",
    "noaa_adapter",
    "weather_mcp_adapter",
    "noaa_coops_adapter",
    "qlib_adapter",
    "Lean_adapter",
    "zipline_adapter",
    "machine_learning_for_trading_adapter",
    "Finance_adapter",
    "mcp_finnhub_adapter",
    "pycot_adapter",
    "cftc_cot_adapter",
    "myeia_adapter",
    "dash_benchmark_adapter",
    "oil_prices_adapter",
    "XAUUSD_LSTM_adapter",
    "quant_trading_adapter",
    "ccxt_adapter",
    "optunahub_adapter",
    "catboost_adapter",
    "statsforecast_adapter",
    "hierarchicalforecast_adapter",
    "utilsforecast_adapter",
    "pytorch_lightning_adapter",
    "auto_sklearn_adapter",
    "wandb_adapter",
    "yfinance_adapter",
    "quantstats_adapter",
    "empyrical_adapter",
    "bt_adapter",
    "ta_adapter",
    "vite_adapter",
    "next.js_adapter",
    "recharts_adapter",
    "dash_adapter",
    "redash_adapter",
    "crewAI_adapter",
    "promptfoo_adapter",
    "awesome_mcp_servers_adapter",
]

PROMOTED_MODULES: dict[str, str] = {
    "SharpAPI_TS_adapter": "sharpapi_ts_adapter",
    "arbitrage_betting_scanner_bot_adapter": "arbitrage_betting_scanner_bot_adapter",
    "NBA_Betting_adapter": "nba_betting_adapter",
    "world_cup_2026_forecast_adapter": "world_cup_2026_forecast_adapter",
    "EuropeanFootballLeaguePredictor_adapter": "europeanfootballleaguepredictor_adapter",
    "noaa_adapter": "noaa_adapter",
    "weather_mcp_adapter": "weather_mcp_adapter",
    "noaa_coops_adapter": "noaa_coops_adapter",
    "qlib_adapter": "qlib_adapter",
    "Lean_adapter": "lean_adapter",
    "zipline_adapter": "zipline_adapter",
    "machine_learning_for_trading_adapter": "machine_learning_for_trading_adapter",
    "Finance_adapter": "finance_adapter",
    "mcp_finnhub_adapter": "mcp_finnhub_adapter",
    "pycot_adapter": "pycot_adapter",
    "cftc_cot_adapter": "cftc_cot_adapter",
    "myeia_adapter": "myeia_adapter",
    "dash_benchmark_adapter": "dash_benchmark_adapter",
    "oil_prices_adapter": "oil_prices_adapter",
    "XAUUSD_LSTM_adapter": "xauusd_lstm_adapter",
    "quant_trading_adapter": "quant_trading_adapter",
    "ccxt_adapter": "ccxt_adapter",
    "optunahub_adapter": "optunahub_adapter",
    "catboost_adapter": "catboost_adapter",
    "statsforecast_adapter": "statsforecast_adapter",
    "hierarchicalforecast_adapter": "hierarchicalforecast_adapter",
    "utilsforecast_adapter": "utilsforecast_adapter",
    "pytorch_lightning_adapter": "pytorch_lightning_adapter",
    "auto_sklearn_adapter": "auto_sklearn_adapter",
    "wandb_adapter": "wandb_adapter",
    "yfinance_adapter": "yfinance_adapter",
    "quantstats_adapter": "quantstats_adapter",
    "empyrical_adapter": "empyrical_adapter",
    "bt_adapter": "bt_adapter",
    "ta_adapter": "ta_adapter",
    "vite_adapter": "vite_adapter",
    "next.js_adapter": "next_js_adapter",
    "recharts_adapter": "recharts_adapter",
    "dash_adapter": "dash_adapter",
    "redash_adapter": "redash_adapter",
    "crewAI_adapter": "crewai_adapter",
    "promptfoo_adapter": "promptfoo_adapter",
    "awesome_mcp_servers_adapter": "awesome_mcp_servers_adapter",
}

