import StageDashboard from './StageDashboard';

const endpoints = [["Session Preflight Controller", "/api/v176/session-preflight-controller"], ["V175 Baseline", "/api/v176/v175-baseline"], ["Controlled Operation Approval Proof", "/api/v176/controlled-operation-approval-proof"], ["Controlled Session Approval Proof", "/api/v176/controlled-session-approval-proof"], ["Pilot Pair Prerequisite Proof", "/api/v176/pilot-pair-prerequisite-proof"], ["Live Submit Caps Snapshot Proof", "/api/v176/live-submit-caps-snapshot-proof"], ["Firewall Adapter Proof", "/api/v176/firewall-adapter-proof"], ["Broker Readonly Proof", "/api/v176/broker-readonly-proof"], ["Candidate Sequence Proof", "/api/v176/candidate-sequence-proof"], ["Per Order Approval Requirement", "/api/v176/per-order-approval-requirement"], ["Limit Only Proof", "/api/v176/limit-only-proof"], ["No Market Order Proof", "/api/v176/no-market-order-proof"], ["Risk Governor Proof", "/api/v176/risk-governor-proof"], ["Abstention Governor Proof", "/api/v176/abstention-governor-proof"], ["Kill Switch Proof", "/api/v176/kill-switch-proof"], ["Rollback Proof", "/api/v176/rollback-proof"], ["Idempotency Proof", "/api/v176/idempotency-proof"], ["Liquidity Slippage Proof", "/api/v176/liquidity-slippage-proof"], ["Max Session Order Count", "/api/v176/max-session-order-count"], ["No Submit Proof", "/api/v176/no-submit-proof"], ["Readiness Governor", "/api/v176/readiness-governor"], ["Execution Lock", "/api/v176/execution-lock"], ["Mission State", "/api/v176/mission-state"]];

const summaryFields = [["Mission", "mission_state_verdict"], ["Session Preflight", "session_preflight_controller_status"], ["Preflight Ready", "session_preflight_ready"], ["Live Orders", "live_orders"], ["Next Action", "current_next_action"], ["Blockers", "current_blockers"]];

export default function V176Dashboard() {
  return <StageDashboard title="Dummy V176 Live Session Final Preflight" endpoints={endpoints} missionKey="dummy_mission_state_report_v162" summaryFields={summaryFields} />;
}
